CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  key_name VARCHAR(128) NOT NULL,
  attempted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX(key_name), INDEX(attempted)
) ENGINE=InnoDB;